name: 'Build and upload SaaS Connector'
description: 'Builds and uploads a SaaS Connector to your Identity Security Cloud Tenant'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '18'
  cli-version:
    description: 'The version of the SailPoint CLI to use'
    required: false
    default: 2.1.5
  connector-alias:
    description: 'The alias of the connector to upload'
    required: true
  base-url: 
    description: 'The base URL of the Identity Security Cloud Tenant'
    required: true
  client-id: 
    description: 'The client ID of the Identity Security Cloud Tenant'
    required: true
  client-secret:
    description: 'The client secret of the Identity Security Cloud Tenant'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check Runner OS
      if: ${{ runner.os != 'Linux' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::Support Linux Only"
        exit 1
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Checkout Connector
      uses: actions/checkout@v2

    - name: Download SailPoint CLI
      shell: bash
      run: |
        wget https://github.com/sailpoint-oss/sailpoint-cli/releases/download/${{ inputs.cli-version }}/sail_${{ inputs.cli-version }}_linux_amd64.deb

    - name: Install SailPoint CLI
      shell: bash
      run: |
        sudo dpkg -i sail_${{ inputs.cli-version }}_linux_amd64.deb
    
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Build Connector
      shell: bash
      run: |
        npm install
        npm run pack-zip
    
    - name: Extract version from package.json
      shell: bash
      run: |  
        echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
        echo "CONNECTOR_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
    
    - name: Upload Connector to ISC
      shell: bash
      run: |
        sail conn upload -c "${{ inputs.connector-alias }}" -f ./dist/${{ env.CONNECTOR_NAME }}-${{ env.PACKAGE_VERSION }}.zip